strings:
  available_for_opportunities: "Открыт к предложениям"
  btn_expand_entry: "[ РАЗВЕРНУТЬ ]"
  btn_collapse_entry: "[ СВЕРНУТЬ ]"
  education: "Образование"
  experience: "Опыт работы"
  footer_text: "Владимир Хальзов · Резюме"
  professional_summary: "Профессиональный профиль"
  technical_skills: "Ключевые навыки"
  languages: "Языки"
  scroll_to_top: "Наверх"
  sidebar_text: "Владимир Хальзов · Резюме"
